#!/usr/bin/env bash
#
# run_tla.sh — run TLC model checking for ZeroGate's TLA+ specifications.
#
# This script is deterministic and CI-friendly. It does NOT fake success: if the
# TLA+ tooling (a Java runtime + tla2tools.jar) is not available, it exits
# non-zero with clear instructions instead of pretending the check passed.
#
# Usage:
#   ./scripts/run_tla.sh quick            Run FrameOwnership for N=3 and N=4 (default)
#   ./scripts/run_tla.sh extended         Run quick set plus deeper N=5 exploration
#   ./scripts/run_tla.sh frame-ownership  Run FrameOwnership with default config (N=3)
#   ./scripts/run_tla.sh --help           Show this help
#
# Tooling discovery (no network downloads in this script):
#   - Java:   uses $JAVA if set, else `java` on PATH.
#   - tla2tools.jar: uses $TLA2TOOLS_JAR (preferred) or the legacy $TLA_TOOLS_JAR
#     if set, else searches a few common locations. Download it once from
#     https://github.com/tlaplus/tlaplus/releases and either put it on one of the
#     searched paths or export TLA2TOOLS_JAR=/path/to/tla2tools.jar.
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

SPEC_DIR="formal/tla"
SPEC="FrameOwnership"
TLA_FILE="${SPEC_DIR}/${SPEC}.tla"

usage() {
    sed -n '2,26p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

if [[ "${1:-quick}" == "--help" || "${1:-quick}" == "-h" ]]; then
    usage
    exit 0
fi

MODE="${1:-quick}"

# --- Locate Java -----------------------------------------------------------
JAVA_BIN="${JAVA:-java}"
if ! command -v "$JAVA_BIN" >/dev/null 2>&1; then
    echo "[run-tla] ERROR: Java runtime not found." >&2
    echo "[run-tla] Install a Java 11+ runtime, or set \$JAVA to its path." >&2
    exit 127
fi

# --- Locate tla2tools.jar --------------------------------------------------
find_tla_jar() {
    # TLA2TOOLS_JAR is the preferred env var; TLA_TOOLS_JAR is kept for back-compat.
    if [[ -n "${TLA2TOOLS_JAR:-}" && -f "${TLA2TOOLS_JAR}" ]]; then
        echo "${TLA2TOOLS_JAR}"
        return 0
    fi
    if [[ -n "${TLA_TOOLS_JAR:-}" && -f "${TLA_TOOLS_JAR}" ]]; then
        echo "${TLA_TOOLS_JAR}"
        return 0
    fi
    local candidates=(
        "${ROOT_DIR}/tla2tools.jar"
        "${ROOT_DIR}/${SPEC_DIR}/tla2tools.jar"
        "${ROOT_DIR}/tools/tla2tools.jar"
        "${HOME}/tla2tools.jar"
        "${HOME}/.tla/tla2tools.jar"
        "/usr/local/lib/tla2tools.jar"
        "/opt/tlaplus/tla2tools.jar"
    )
    local c
    for c in "${candidates[@]}"; do
        if [[ -f "$c" ]]; then
            echo "$c"
            return 0
        fi
    done
    return 1
}

if ! TLA_JAR="$(find_tla_jar)"; then
    echo "[run-tla] ERROR: tla2tools.jar not found." >&2
    echo "[run-tla] Download it from https://github.com/tlaplus/tlaplus/releases" >&2
    echo "[run-tla] then set TLA2TOOLS_JAR=/path/to/tla2tools.jar, or place it at" >&2
    echo "[run-tla]   ${ROOT_DIR}/tla2tools.jar" >&2
    exit 127
fi

echo "[run-tla] repo root:     ${ROOT_DIR}"
echo "[run-tla] java:          $("$JAVA_BIN" -version 2>&1 | head -n1)"
echo "[run-tla] tla2tools.jar: ${TLA_JAR}"

# --- TLC runner ------------------------------------------------------------
# run_tlc <N> : run FrameOwnership with a temporary config overriding N.
run_tlc() {
    local n="$1"
    local cfg
    cfg="$(mktemp -t frameownership_n${n}.XXXXXX.cfg)"
    # Build a config identical to the committed one but with the requested N.
    {
        echo "\\* Auto-generated by scripts/run_tla.sh for N=${n}."
        echo "CONSTANTS"
        echo "    N = ${n}"
        echo "SPECIFICATION"
        echo "    Spec"
        echo "INVARIANTS"
        echo "    TypeOK"
        echo "    FrameInExactlyOneState"
        echo "    FreeListOnlyFree"
        echo "    FreeListMatchesState"
        echo "    NonFreeNotInFree"
        echo "    TxNotFreeBeforeCompletion"
        echo "    UserNotFree"
        echo "    RxNotFree"
        echo "    InFillNotFree"
        echo "    KernelNotFree"
        echo "    CompletionNotFree"
        echo "    OwnershipConsistent"
    } > "$cfg"

    echo ""
    echo "[run-tla] === ${SPEC} (N=${n}) ==="
    # -cleanup removes TLC's states/ output so CI stays clean.
    (
        cd "$SPEC_DIR"
        "$JAVA_BIN" -XX:+UseParallelGC -cp "$TLA_JAR" tlc2.TLC \
            -config "$cfg" -cleanup -nowarning "${SPEC}.tla"
    )
    rm -f "$cfg"
}

run_default() {
    echo ""
    echo "[run-tla] === ${SPEC} (default config ${SPEC_DIR}/${SPEC}.cfg) ==="
    (
        cd "$SPEC_DIR"
        "$JAVA_BIN" -XX:+UseParallelGC -cp "$TLA_JAR" tlc2.TLC \
            -config "${SPEC}.cfg" -cleanup -nowarning "${SPEC}.tla"
    )
}

case "$MODE" in
    quick)
        run_tlc 3
        run_tlc 4
        ;;
    extended)
        run_tlc 3
        run_tlc 4
        # N=5 is a deeper but still finite exploration. Symmetry reduction is
        # NOT implemented in FrameOwnership.tla, so larger N (e.g. N=8) is not
        # offered here to avoid an unbounded/expensive run. Adding a symmetry
        # set is tracked as future spec work; do not claim N=8 until it exists.
        run_tlc 5
        echo ""
        echo "[run-tla] NOTE: N>=8 / symmetry-reduced checking is not yet supported."
        echo "[run-tla]       It is intentionally NOT run (would be expensive without symmetry)."
        ;;
    frame-ownership)
        run_default
        ;;
    *)
        echo "[run-tla] ERROR: unknown mode '${MODE}'" >&2
        echo "" >&2
        usage >&2
        exit 2
        ;;
esac

echo ""
echo "[run-tla] All requested TLC checks passed."
